language: node_js
node_js:
  - 4

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser  # Karma CI
  - export DISPLAY=:99.0
  - cd frontend

before_script:
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c webdriver-manager start 2>&1 &  # Protractor CI
  - sleep 1  # give server time to start

after_failure:
  - cat /home/travis/build/Svjard/flightpath/npm-debug.log

branches:
  only: master

notifications:
  email: true

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=2ed7b4d20b9686ce18a95289d0d319f76f0a163f

cache:
  directories: node_modules